//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdq_finserv.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RDQFinservEntities : DbContext
    {
        public RDQFinservEntities()
            : base("name=RDQFinservEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_User> Admin_User { get; set; }
        public virtual DbSet<sign_up> sign_up { get; set; }
        public virtual DbSet<STAY_IN_TOUCH> STAY_IN_TOUCH { get; set; }
        public virtual DbSet<VISITOR_LOG> VISITOR_LOG { get; set; }
    }
}
