//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdq_finserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITOR_LOG
    {
        public int SLNO { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string VISITORINFO { get; set; }
        public string COUNTRY { get; set; }
        public string REGION { get; set; }
        public string REGION_NAME { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string ISP { get; set; }
        public string ORG { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUTDE { get; set; }
        public string ACTION { get; set; }
    }
}
